# Generated by Django 5.2.13 on 2026-04-09 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_staff_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(choices=[(30, '30 Minutes'), (60, '60 Minutes')], default=60),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated from therapy type and duration', max_digits=10),
        ),
        migrations.CreateModel(
            name='TherapyType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_30', models.DecimalField(decimal_places=2, help_text='Session price for 30 minutes', max_digits=10, verbose_name='Price (30 min)')),
                ('price_60', models.DecimalField(decimal_places=2, help_text='Session price for 60 minutes', max_digits=10, verbose_name='Price (60 min)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.therapytype'),
        ),
    ]
