# Generated by Django 5.2.13 on 2026-04-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_is_absent_appointment_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='needs_reassignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reassignment_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
