# Generated by Django 5.2.13 on 2026-04-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapytype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='therapytype',
            name='updated_by',
        ),
    ]
