# Generated by Django 5.2.13 on 2026-04-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancemark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemark',
            name='status',
            field=models.CharField(choices=[('half_day', 'Half-day'), ('leave', 'Leave')], max_length=10),
        ),
    ]
